In [37]:

#Importing libraries

import numpy as np
import pandas as pd
import tensorflow as tf

tf.__version__

"""#Importing dataset

*   Có 14 cột và tính cột đầu tiên là 0. Cột 0-13 cho x
*   Cột thứ 14 (cột cuối cùng) thể hiện kết quả bệnh nhân có bị cơn đau hay không
"""

dataset = pd.read_csv('/content/heart.csv')
x = dataset.iloc[:, 0:13].values
y = dataset.iloc[:, -1].values


print(x)

print(y)

"""
    #Sử dụng train_test_split để chia dữ liệu thành tập huấn luyện và tập kiểm thử.
"""
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

"""#Chuẩn hoá dữ liệu"""

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

"""#Khởi tạo ann"""

ann = tf.keras.models.Sequential()

"""#Lớp đầu vào và lớp ẩn đầu tiên (units là ngẫu nhiên , vì vậy ta sẽ chọn 7)"""

ann.add(tf.keras.layers.Dense(units=7,activation='relu'))

"""#Lớp ẩn thứ hai bổ sung (đơn vị là 1 vì kết quả chỉ là 0 hoặc 1)"""

ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

"""#Biên dịch ANN"""

ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

"""#ANN huấn luyện trên tập huấn luyện (kích thước 32 là mặc định)"""

ann.fit(x_train,y_train,batch_size=32,epochs=100)

"""# Dự đoán - một người có các đặc điểm sau có bị đau tim hay không. 0 = không/ít khả năng bị đau tim HOẶC 1 = nhiều khả năng bị đau tim

* 1) age=50
* 2) sex=1 (male)
* 3) chest pain type (4 values)=1
* 4) resting blood pressure=172
* 5) serum cholestoral in mg/dl=221
* 6)fasting blood sugar > 120 mg/dl=1
* 7) resting electrocardiographic results (values 0,1,2)=0
* 8) maximum heart rate achieved=160
* 9) exercise induced angina=0
* 10) oldpeak = ST depression induced by exercise relative to rest=1.5
* 11)the slope of the peak exercise ST segment=1
* 12) number of major vessels (0-3) colored by flourosopy=3
* 13) thal: 0 = normal; 1 = fixed defect; 2 = reversable defect=2
"""

print("Tỉ lệ bị bênh tim: " ,ann.predict(sc.transform([[50,1,1,172,221,1,0,160,0,1.5,1,3,2]])))


0.19801980198019803
[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]
Epoch 1/100
8/8 [==============================] - 1s 5ms/step - loss: 0.8470 - accuracy: 0.3992
Epoch 2/100
8/8 [==============================] - 0s 4ms/step - loss: 0.82

# Mục mới

# Mục mới